version: '3.4'

services:
  client-app:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    depends_on:  
      - server
    ports:
      - 3000:3000
    network_mode: "host"
  server:
    image: server
    build:
      context: ws-server
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    network_mode: "host"
